# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [6]:
import numpy as np
import random

#### 2. Print your NumPy version.

In [5]:
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
array_1 = np.random.rand(2,3,5)

array_1

array([[[0.44345502, 0.44518657, 0.03270929, 0.41429688, 0.58258845],
        [0.64300406, 0.97458802, 0.918499  , 0.18171223, 0.95225118],
        [0.00356952, 0.96329753, 0.69960377, 0.34059741, 0.73545513]],

       [[0.46084473, 0.68960848, 0.31118119, 0.00694049, 0.61554755],
        [0.67399441, 0.87872417, 0.60024968, 0.13403651, 0.20370838],
        [0.47549899, 0.40899375, 0.02343915, 0.2513997 , 0.58971082]]])

In [14]:
# Method 2
array_2 = np.random.randint(low=0 , high=100,size=(2,3,5))

array_2

array([[[56, 58, 73, 37, 33],
        [75, 62, 26, 69, 71],
        [68, 56, 62, 14, 46]],

       [[72, 85, 54, 22, 41],
        [99, 56, 76,  1, 48],
        [99, 83, 95,  1, 95]]])

In [15]:
# Method 3
array_3 = np.random.uniform(low=0, high=100, size=(2,3,5))

array_3

array([[[39.64157941, 77.75064771,  8.98353895, 74.21958303,
         86.38138134],
        [24.34398434, 72.17567774, 35.90556417, 89.22322186,
         73.4450289 ],
        [ 6.29748147, 92.18037472, 30.31743389, 26.73726385,
         51.64908056]],

       [[94.01704013, 29.83977078, 44.87055645, 45.28800602,
         62.81538889],
        [93.86779397, 59.31512233, 78.71518655, 87.72510771,
         54.10632489],
        [ 0.67953244, 66.54107702, 39.58980994, 28.58723016,
         70.5073435 ]]])

#### 4. Print *a*.


In [18]:
a = array_1
print(a)

[[[0.44345502 0.44518657 0.03270929 0.41429688 0.58258845]
  [0.64300406 0.97458802 0.918499   0.18171223 0.95225118]
  [0.00356952 0.96329753 0.69960377 0.34059741 0.73545513]]

 [[0.46084473 0.68960848 0.31118119 0.00694049 0.61554755]
  [0.67399441 0.87872417 0.60024968 0.13403651 0.20370838]
  [0.47549899 0.40899375 0.02343915 0.2513997  0.58971082]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [23]:
b = np.full(shape=(5,2,3), fill_value=1)

b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [24]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
# np.array_equal compares i f2 arrays have same size & same shape - here False
np.array_equal(a,b)

# array.size == allows to compare both sizes
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
#No Addition impossible because they have different shapes - trying to adding them returns ValueError
# Needs to be transpose firts
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [40]:
# there is an error in the instruction - original b array is 5x2x3 (cf. question 5)
# simply transposing array b would make it 3x2x5 - NOT 2x3x5 as expected in this instruction
c = b.transpose()
c.shape
print('c shape is ', c.shape, 'not the size expected because of wrong b shape')

# needs to reshape b to the required structure to make it possible to add to a
c = np.resize(b, (2,3,5))
print('c shape is now at the correct size', c.shape)

c shape is  (3, 2, 5) not the size expected because of wrong b shape
c shape is now at the correct size (2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [44]:
d = a + c
print(d)
print('\n works now because both matrices a & c have the same shape')

[[[1.44345502 1.44518657 1.03270929 1.41429688 1.58258845]
  [1.64300406 1.97458802 1.918499   1.18171223 1.95225118]
  [1.00356952 1.96329753 1.69960377 1.34059741 1.73545513]]

 [[1.46084473 1.68960848 1.31118119 1.00694049 1.61554755]
  [1.67399441 1.87872417 1.60024968 1.13403651 1.20370838]
  [1.47549899 1.40899375 1.02343915 1.2513997  1.58971082]]]

 works now because both matrices a & c have the same shape


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
#both matrices have the same shape (2x3x5) - making addition operation possible
print(a)
#array a is equal to random float number
print(d)
#array d is equal to a + 1 : due to adding up original b matrix (all made of 1) to a

[[[0.44345502 0.44518657 0.03270929 0.41429688 0.58258845]
  [0.64300406 0.97458802 0.918499   0.18171223 0.95225118]
  [0.00356952 0.96329753 0.69960377 0.34059741 0.73545513]]

 [[0.46084473 0.68960848 0.31118119 0.00694049 0.61554755]
  [0.67399441 0.87872417 0.60024968 0.13403651 0.20370838]
  [0.47549899 0.40899375 0.02343915 0.2513997  0.58971082]]]
[[[1.44345502 1.44518657 1.03270929 1.41429688 1.58258845]
  [1.64300406 1.97458802 1.918499   1.18171223 1.95225118]
  [1.00356952 1.96329753 1.69960377 1.34059741 1.73545513]]

 [[1.46084473 1.68960848 1.31118119 1.00694049 1.61554755]
  [1.67399441 1.87872417 1.60024968 1.13403651 1.20370838]
  [1.47549899 1.40899375 1.02343915 1.2513997  1.58971082]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [57]:
e = np.multiply(a,c) 

e

array([[[0.44345502, 0.44518657, 0.03270929, 0.41429688, 0.58258845],
        [0.64300406, 0.97458802, 0.918499  , 0.18171223, 0.95225118],
        [0.00356952, 0.96329753, 0.69960377, 0.34059741, 0.73545513]],

       [[0.46084473, 0.68960848, 0.31118119, 0.00694049, 0.61554755],
        [0.67399441, 0.87872417, 0.60024968, 0.13403651, 0.20370838],
        [0.47549899, 0.40899375, 0.02343915, 0.2513997 , 0.58971082]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [47]:
#multiplying all elements of a by 1 (all values from c) 1*a = a - #itsOnlyLogical
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [48]:
np.array_equal(a,e)

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [51]:
d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

1.9745880244250844
1.0035695239388231
1.4884897353682631


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [55]:
f = np.empty((2,3,5))

In [56]:
f

array([[[1.44345502, 1.44518657, 1.03270929, 1.41429688, 1.58258845],
        [1.64300406, 1.97458802, 1.918499  , 1.18171223, 1.95225118],
        [1.00356952, 1.96329753, 1.69960377, 1.34059741, 1.73545513]],

       [[1.46084473, 1.68960848, 1.31118119, 1.00694049, 1.61554755],
        [1.67399441, 1.87872417, 1.60024968, 1.13403651, 1.20370838],
        [1.47549899, 1.40899375, 1.02343915, 1.2513997 , 1.58971082]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [69]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean :
                f[i][j][k] = 50
            elif d[i][j][k] == d_min :
                f[i][j][k] = 0
            else:
                f[i][j][k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [71]:
f

array([[[ 25.,  25.,  25.,  25.,  75.],
        [ 75., 100.,  75.,  25.,  75.],
        [  0.,  75.,  75.,  25.,  75.]],

       [[ 25.,  75.,  25.,  25.,  75.],
        [ 75.,  75.,  75.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [72]:
#last for loop method does not work because ValueError = impossible to convert to str

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 'A'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 'B'
            elif d[i][j][k] == d_mean :
                f[i][j][k] = 'C'
            elif d[i][j][k] == d_min :
                f[i][j][k] = 'D'
            else:
                f[i][j][k] = 'E'

ValueError: could not convert string to float: 'A'

In [96]:
# creating empty array to populate while iterating through d
# static varialbe encoding with STR value - to populate g with strings 
g = np.empty((2,3,5), dtype=str)

In [97]:
iteration = np.nditer(d,flags=['multi_index'])

In [98]:
while not iteration.finished:
    if iteration[0] == d_min:
        g[iteration.multi_index] = 'A'
    elif iteration[0] > d_min and iteration[0] < d_mean:
        g[iteration.multi_index] = 'B'
    elif iteration[0] == d_mean:
        g[iteration.multi_index] = 'C'
    elif iteration[0] > d_mean and iteration[0] < d_max:
        g[iteration.multi_index] = 'D'
    else:
        g[iteration.multi_index] = 'E'
    iteration.iternext()

In [99]:
g

array([[['B', 'B', 'B', 'B', 'D'],
        ['D', 'E', 'D', 'B', 'D'],
        ['A', 'D', 'D', 'B', 'D']],

       [['B', 'D', 'B', 'B', 'D'],
        ['D', 'D', 'D', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'D']]], dtype='<U1')